### ISSUE TITLE
Error when installing composer dependencies.

### ISSUE THREAD

**Issue by aaronware** [impresscms-dev/phpdocs-wiki-update-action#90]
Composer installs properly locally and installs properly in another workflow. But for this action, it dies with the following error. Sorry, I cannot share the entire composer.json but this is a breakdown of the relevant parts.

`...
  "require": {
    "php": ">=7.3",
    "symfony/http-client": "^5.2",
    "nyholm/psr7": "^1.4",
    "cmb2/cmb2": "^2.9",
    "composer/installers": "^1.11",
    "nicolab/php-ftp-client": "^1.5",
    "phpseclib/phpseclib": "~3.0"
  },
  "autoload": {
    "psr-4": {
      "Custom\\": "application/"
    },
    "files": ["vendor/cmb2/cmb2/init.php"]
  },
  "scripts": {
    "lint": "phpcs .",
    "lint-fix": "phpcbf ."
  },
  "require-dev": {
    "wsdltophp/packagegenerator": "^3.3"
  }
...`

`Error: Error: Execution failed
Error:     at ExecutionHandler.getResults (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:355:15)
Error:     at ComposerHandler.getResults (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:4401:36)
Error:     at ComposerHandler.run (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:4410:14)
Error:     at GlobalInstallAction.exec (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:1779:28)
Error:     at Object.325 (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:1267:16)
Error:     at __webpack_require__ (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:22:30)
Error:     at startup (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:37:19)
Error:     at /home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:41:18
Error:     at Object.<anonymous> (/home/runner/work/_actions/impresscms-dev/phpdocs-wiki-update-action/v1.0.0/dist/index.js:44:10)
Error:     at Module._compile (internal/modules/cjs/loader.js:959:30)
Error: Execution failed`

**Comment by aaronware** [comment]
Well, I think it was due to an extension. This project requires soap. I ended up using `php-actions/composer@v5` to install the dependencies and have the soap extension as well. However, now I do not get an error but I never seem to get past the following screenshot. I do not see any new pages in the Wiki so I assume it's hung up on something else, however, no details are being output to the console

![Screen Shot 2021-06-10 at 1 58 00 PM](https://user-images.githubusercontent.com/3390827/121574239-0fd8c600-c9f4-11eb-82f1-884f7a298f99.png)

Any help would be appreciated. Is there a flag to remove dependency installation?

**Comment by aaronware** [comment]
After a few more minutes the action finally errored out. It appears it did install what it needed. It tried to clone the old repo wiki then appeared to fail when trying to remove dev requirements.

![Screen Shot 2021-06-10 at 2 03 45 PM](https://user-images.githubusercontent.com/3390827/121575024-e3717980-c9f4-11eb-845b-3cd2402576b5.png)

I'm not sure why the composer dependency needs to be coupled with the action as there are a ton of actions that handle that part well. But far be it from me to tell you how to write or support your action. But hopefully, this helps any one else as it may be an issue if a project needs any PHP extensions that aren't available "out of the box" on a clean github action

**Comment by MekDrop** [comment]
Thank you for your feedback. First I though that I'll could find some solutions for your pointed issues faster but I think I will need probably at least few weeks for that. Sorry, my delay.

**Comment by MekDrop** [comment]
Sorry, @aaronware for me it took some time to figure it out how to solve your issue. 

From now it is possible to use `setup_php` parameter with `false` value. This parameter says that the user wants by himself to specify PHP extensions and other related stuff. F.e. user can now run `shivammathur/setup-php` before this update wiki action. 

Also, from now some code that generates wiki is isolated. So, there is less possibility that problems like yours could happen.
